apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubegram-sidecar.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubegram-sidecar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kubegram-sidecar.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
