{{- if .Values.kubegram.serverToken }}
apiVersion: v1
kind: Secret
metadata:
  name: kubegram-operator-secret
  labels:
    {{- include "kubegram-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  server-token: {{ .Values.kubegram.serverToken | quote }}
{{- end }}
