/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  GraphContext,  ManifestItem,  ManifestsResponse,  NodeContext,  OpenApiPathEntry,  RAGContextInput,  TestCaseSummary,  TestResultSummary,  UserContextInput,  ValidationAnalysisResponse,  ValidationStats,  ValidationTestCaseOutput,  ValidationTestCasesResponse } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface GraphContext {
      graph_name?: string | null
      default_namespace?: string | null
      total_nodes?: number | null
      node_types?: string | null
    }
    export interface ManifestItem {
      file_name?: string | null
      generated_code?: string | null
      assumptions: string[]
      decisions: string[]
      commands?: string[] | null
      entity_name?: string | null
      entity_id?: string | null
      entity_type?: string | null
    }
    export interface ManifestsResponse {
      manifests: ManifestItem[]
    }
    export interface NodeContext {
      id?: string | null
      name?: string | null
      node_type?: string | null
      k8s_namespace?: string | null
      is_external?: boolean | null
      language?: string | null
      framework?: string | null
      container_image?: string | null
      replicas?: number | null
      ports: number[]
      engine?: string | null
      version?: string | null
      storage_size?: string | null
      storage_class?: string | null
      max_memory?: string | null
      persistence?: boolean | null
      cluster_mode?: boolean | null
      partitions?: number | null
      replication_factor?: number | null
      management_port?: number | null
      kind?: string | null
      algorithm?: string | null
      upstreams: string[]
      backends: string[]
      routes: string[]
      domains: string[]
      tls_enabled?: boolean | null
      auth_enabled?: boolean | null
      cors_enabled?: boolean | null
      rate_limit_enabled?: boolean | null
      scrape_interval?: string | null
      retention_period?: string | null
      alertmanager?: boolean | null
      health_check_path?: string | null
      external_host?: string | null
      external_provider?: string | null
      env_vars?: string | null
      resources?: string | null
      secret_names: string[]
    }
    export interface OpenApiPathEntry {
      path?: string | null
      methods?: string | null
    }
    export interface RAGContextInput {
      context_text?: string | null
    }
    export interface TestCaseSummary {
      correlationId?: string | null
      method?: string | null
      path?: string | null
      expectedStatus?: number | null
    }
    export interface TestResultSummary {
      correlationId?: string | null
      success?: boolean | null
      actualStatus?: number | null
      responseTimeMs?: number | null
      error?: string | null
    }
    export interface UserContextInput {
      system_messages: string[]
      user_requirements: string[]
      planning_context: string[]
    }
    export interface ValidationAnalysisResponse {
      analysisText?: string | null
    }
    export interface ValidationStats {
      total?: number | null
      passed?: number | null
      failed?: number | null
      skipped?: number | null
    }
    export interface ValidationTestCaseOutput {
      method?: string | null
      path?: string | null
      headers: Record<string, string>
      body?: string | null
      expectedStatus?: number | null
    }
    export interface ValidationTestCasesResponse {
      testCases: ValidationTestCaseOutput[]
    }
}