/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    GraphContext: ClassViewer<'GraphContext', "graph_name" | "default_namespace" | "total_nodes" | "node_types">;
    
    ManifestItem: ClassViewer<'ManifestItem', "file_name" | "generated_code" | "assumptions" | "decisions" | "commands" | "entity_name" | "entity_id" | "entity_type">;
    
    ManifestsResponse: ClassViewer<'ManifestsResponse', "manifests">;
    
    NodeContext: ClassViewer<'NodeContext', "id" | "name" | "node_type" | "k8s_namespace" | "is_external" | "language" | "framework" | "container_image" | "replicas" | "ports" | "engine" | "version" | "storage_size" | "storage_class" | "max_memory" | "persistence" | "cluster_mode" | "partitions" | "replication_factor" | "management_port" | "kind" | "algorithm" | "upstreams" | "backends" | "routes" | "domains" | "tls_enabled" | "auth_enabled" | "cors_enabled" | "rate_limit_enabled" | "scrape_interval" | "retention_period" | "alertmanager" | "health_check_path" | "external_host" | "external_provider" | "env_vars" | "resources" | "secret_names">;
    
    RAGContextInput: ClassViewer<'RAGContextInput', "context_text">;
    
    UserContextInput: ClassViewer<'UserContextInput', "system_messages" | "user_requirements" | "planning_context">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "GraphContext","ManifestItem","ManifestsResponse","NodeContext","RAGContextInput","UserContextInput",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.GraphContext = this.tb.classViewer("GraphContext", [
          "graph_name","default_namespace","total_nodes","node_types",
        ]);
        
        this.ManifestItem = this.tb.classViewer("ManifestItem", [
          "file_name","generated_code","assumptions","decisions","commands","entity_name","entity_id","entity_type",
        ]);
        
        this.ManifestsResponse = this.tb.classViewer("ManifestsResponse", [
          "manifests",
        ]);
        
        this.NodeContext = this.tb.classViewer("NodeContext", [
          "id","name","node_type","k8s_namespace","is_external","language","framework","container_image","replicas","ports","engine","version","storage_size","storage_class","max_memory","persistence","cluster_mode","partitions","replication_factor","management_port","kind","algorithm","upstreams","backends","routes","domains","tls_enabled","auth_enabled","cors_enabled","rate_limit_enabled","scrape_interval","retention_period","alertmanager","health_check_path","external_host","external_provider","env_vars","resources","secret_names",
        ]);
        
        this.RAGContextInput = this.tb.classViewer("RAGContextInput", [
          "context_text",
        ]);
        
        this.UserContextInput = this.tb.classViewer("UserContextInput", [
          "system_messages","user_requirements","planning_context",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}