/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface GraphContext {
  graph_name: string
  default_namespace: string
  total_nodes: number
  node_types: string
  
}

export interface ManifestItem {
  file_name: string
  generated_code: string
  assumptions: string[]
  decisions: string[]
  commands?: string[] | null
  entity_name: string
  entity_id?: string | null
  entity_type?: string | null
  
}

export interface ManifestsResponse {
  manifests: ManifestItem[]
  
}

export interface NodeContext {
  id: string
  name: string
  node_type: string
  k8s_namespace: string
  is_external: boolean
  language?: string | null
  framework?: string | null
  container_image?: string | null
  replicas?: number | null
  ports: number[]
  engine?: string | null
  version?: string | null
  storage_size?: string | null
  storage_class?: string | null
  max_memory?: string | null
  persistence?: boolean | null
  cluster_mode?: boolean | null
  partitions?: number | null
  replication_factor?: number | null
  management_port?: number | null
  kind?: string | null
  algorithm?: string | null
  upstreams: string[]
  backends: string[]
  routes: string[]
  domains: string[]
  tls_enabled?: boolean | null
  auth_enabled?: boolean | null
  cors_enabled?: boolean | null
  rate_limit_enabled?: boolean | null
  scrape_interval?: string | null
  retention_period?: string | null
  alertmanager?: boolean | null
  health_check_path?: string | null
  external_host?: string | null
  external_provider?: string | null
  env_vars?: string | null
  resources?: string | null
  secret_names: string[]
  
}

export interface OpenApiPathEntry {
  path: string
  methods: string
  
}

export interface RAGContextInput {
  context_text?: string | null
  
}

export interface TestCaseSummary {
  correlationId: string
  method: string
  path: string
  expectedStatus: number
  
}

export interface TestResultSummary {
  correlationId: string
  success: boolean
  actualStatus: number
  responseTimeMs: number
  error?: string | null
  
}

export interface UserContextInput {
  system_messages: string[]
  user_requirements: string[]
  planning_context: string[]
  
}

export interface ValidationAnalysisResponse {
  analysisText: string
  
}

export interface ValidationStats {
  total: number
  passed: number
  failed: number
  skipped: number
  
}

export interface ValidationTestCaseOutput {
  method: string
  path: string
  headers: Record<string, string>
  body?: string | null
  expectedStatus: number
  
}

export interface ValidationTestCasesResponse {
  testCases: ValidationTestCaseOutput[]
  
}
