apiVersion: v1
kind: Service
metadata:
  name: kubegram-github-app
  namespace: kubegram
  labels:
    app: kubegram-github-app
    component: github-integration
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: kubegram-github-app
    component: github-integration