//go:build linux

// Code generated by bpf2go; DO NOT EDIT.
// Run `go generate ./pkg/ebpf/` on a Linux host with clang + libbpf-dev installed
// to regenerate from bpf/tracer.c.
//
// This stub satisfies the compiler until the real generated file is produced.
// The real bpf2go output will overwrite this file with embedded eBPF bytecode.

package ebpf

import (
	"fmt"

	ciliumebpf "github.com/cilium/ebpf"
	"github.com/cilium/ebpf/ringbuf"
)

// tracerObjects holds all eBPF maps and programs loaded from tracer.c.
// The real version embeds the compiled BPF ELF object as a Go byte slice.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
}

func (o *tracerObjects) Close() {
	o.tracerPrograms.Close()
	o.tracerMaps.Close()
}

type tracerPrograms struct {
	TcIngress *ciliumebpf.Program `ebpf:"tc_ingress"`
	TcEgress  *ciliumebpf.Program `ebpf:"tc_egress"`
}

func (p *tracerPrograms) Close() {
	if p.TcIngress != nil {
		p.TcIngress.Close()
	}
	if p.TcEgress != nil {
		p.TcEgress.Close()
	}
}

type tracerMaps struct {
	Events  *ciliumebpf.Map `ebpf:"events"`
	Scratch *ciliumebpf.Map `ebpf:"scratch"`
}

func (m *tracerMaps) Close() {
	if m.Events != nil {
		m.Events.Close()
	}
	if m.Scratch != nil {
		m.Scratch.Close()
	}
}

// loadTracerObjects is a stub. The real implementation (generated by bpf2go)
// loads a compiled BPF ELF blob embedded in the binary.
// Run `go generate ./pkg/ebpf/` to produce the real version.
func loadTracerObjects(obj *tracerObjects, _ *ciliumebpf.CollectionOptions) error {
	return fmt.Errorf("eBPF object not compiled: run `go generate ./pkg/ebpf/` on Linux with clang + libbpf-dev")
}

// Ensure ringbuf is referenced so the import is not removed by goimports.
var _ = ringbuf.ErrClosed
